# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: braillel_rules.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'braillel_rules.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62raillel_rules.proto\x12\x0e\x62raillel_rules\"]\n\x0cPartOfSpeech\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x13\n\x0b\x42\x65\x66oreSpace\x18\x02 \x01(\x08\x12\x12\n\nAfterSpace\x18\x03 \x01(\x08\x12\x16\n\x0e\x41llowLineBreak\x18\x04 \x01(\x08\"a\n\x04Rule\x12-\n\x07\x63urrent\x18\x01 \x01(\x0b\x32\x1c.braillel_rules.PartOfSpeech\x12*\n\x04next\x18\x02 \x03(\x0b\x32\x1c.braillel_rules.PartOfSpeech\"3\n\x0c\x42railleRules\x12#\n\x05rules\x18\x01 \x03(\x0b\x32\x14.braillel_rules.Ruleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'braillel_rules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARTOFSPEECH']._serialized_start=40
  _globals['_PARTOFSPEECH']._serialized_end=133
  _globals['_RULE']._serialized_start=135
  _globals['_RULE']._serialized_end=232
  _globals['_BRAILLERULES']._serialized_start=234
  _globals['_BRAILLERULES']._serialized_end=285
# @@protoc_insertion_point(module_scope)
