rule {
  current_pos {
    name: "名詞"
  }
  next_pos {
    name: "動詞"
    before_space: true
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "代名詞"
  }
  next_pos {
    name: "括弧開"
    before_space: true
  }
}
rule {
  current_pos {
    name: "動詞"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  next_pos {
    name: "*"
    before_space: false
  }
}
rule {
  current_pos {
    name: "助動詞"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  next_pos {
    name: "動詞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "助詞"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  next_pos {
    name: "動詞"
    before_space: true
  }
  next_pos {
    name: "形容詞"
    before_space: true
  }
  next_pos {
    name: "*"
    before_space: false
  }
}
rule {
  current_pos {
    name: "形容詞"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  next_pos {
    name: "動詞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "副詞"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  next_pos {
    name: "動詞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "数詞"
  }
  next_pos {
    name: "助数詞可能"
    before_space: false
  }
}
rule {
  current_pos {
    name: "助数詞可能"
  }
  next_pos {
    name: "助数詞可能"
    before_space: false
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "括弧閉"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  next_pos {
    name: "代名詞"
    before_space: true
  }
  next_pos {
    name: "動詞"
    before_space: true
  }
}
rule {
  current_pos{
    name: "*"
  }
  next_pos {
    name: "*"
    before_space: false
  }
}
