[project]
name = "momobrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KIRIAKE Masanori", email = "seiken@rd01.net" }
]
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "protobuf>=6.33.1",
    "sudachidict-core>=20251022",
    "sudachipy>=0.6.10",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
[project.scripts]
momo = "momobrl.__init__:main"