[project]
name = "momobrl"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KIRIAKE Masanori", email = "seiken@rd01.net" }
]
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "sklearn-crfsuite>=0.5.0",
    "protobuf",
    "sudachidict-core",
    "sudachipy",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
[project.scripts]
neomomo = "momobrl.main:main"
