[project]
name = "momobrl"
version = "0.2.0"
description = "A tool to convert Japanese text to Braille using machine learning."
readme = "README.md"
authors = [
    { name = "KIRIAKE Masanori", email = "seiken@rd01.net" }
]
requires-python = ">=3.13"
dependencies = [
    "loguru",
    "sklearn-crfsuite",
    "protobuf",
    "sudachidict-core",
    "sudachipy",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
[project.scripts]
momo = "momobrl.main:main"
