[package]
name = "momors-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Japanese text to Braille converter"

[package.metadata.wix]
eula = false

[[bin]]
name = "momo"
path = "src/main.rs"

[dependencies]
momors-core.workspace = true
momors-braille.workspace = true
clap.workspace = true
