# 日本語の品詞に基づくルール
# ルールの先頭から順番に評価され、スコアがつけられる。スコアが最も高いルールが採用される。
# ルールを追加する際はルールの先頭に簡単な例文を添えること
# ルールの評価は、現在の品詞と次の品詞に基づいて行われる。
rule {
  # 一般的な自立語
  # 例： 点字
  current_pos {
    name: "名詞"
    name: "固有名詞"
    name: "副詞"
    name: "形容詞"
  }
  # 一般的な自立語が続く
  # 例: 点字図書館
  next_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "人名"
    name: "動詞"
    before_space: true
  }
}
# 助詞
# 例： が・は・へ・を・に…
# 多くの場合助詞の後は空ける
rule {
  current_pos {
    name: "助詞"
    name: "助動詞"
  }
  # 助詞が・助動詞続く
  # 例: 私のが、見ました → 「まし」・「た」はどちらも助動詞
  next_pos {
    name: "助詞"
    name: "助動詞"
    before_space: false
  }
  # 句読点など
  # 変換して、→「て」は助詞
  next_pos {
    name: "補助記号"
    reading_word_match: "。"
    reading_word_match: "、"
    reading_word_match: "・"
    before_space: false
  }
  # その他の品詞が続く
  # 私の椅子
  next_pos {
    name: "*"
    before_space: true
  }
}
# 動詞
# 例： 行く・来る・する…
# 動詞の後は空ける
rule {
  current_pos {
    name: "動詞"
  }
  # 自立語
  # 例: 走る人
  next_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "人名"
    before_space: true
  }
}
# 数字とそれに関連するルール
# 例： 2025年
rule {
  current_pos {
    name: "数詞"
    name: "助数詞"
    name: "助数詞可能"
  }
  # 助数詞など
  # 例: １冊・９０年代・３冊の
  next_pos {
    name: "助数詞"
    name: "助数詞可能"
    name: "助詞"
    before_space: false
  }
  # 助数詞の後に一般的な品詞が続く
  # 例: １軒となりのいえ
  next_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "人名"
    name: "形容詞"
    name: "動詞"
    name: "副詞"
    before_space: true
  }
}
# フォールバックルール
# その他の品詞はとりあえず続けてみる
rule {
  current_pos {
    name: "*"
  }
  # 句読点などの記号
  # 実例は設定参照
  next_pos {
    name: "補助記号"
    before_space: false
  }
}
