[project]
name = "neomomo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "gunicorn>=25.1.0",
    "momo-py",
    "requests>=2.32.5",
]

[tool.uv.sources]
momo-py = { git = "https://github.com/ji6czd/momo", subdirectory = "momo-py", branch = "LR_feature"}


