[workspace]
resolver = "3"
members = [
    "crates/momors-core",
    "crates/momors-braille",
    "crates/momors-cli",
    "crates/momors-ffi",
    "crates/momors-pyo3",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["KIRIAKE Masanori <seiken@rd01.net>"]
license = "BSD-3-Clause"

[workspace.dependencies]
thiserror = "1.0"
clap = { version = "4", features = ["derive"] }
byteorder = "1.5"
momors-core = { path = "crates/momors-core", version = "0.1.0" }
momors-braille = { path = "crates/momors-braille", version = "0.1.0" }
