# 日本語の品詞に基づくルール
# ルールの先頭から順番に評価され、スコアがつけられる。スコアが最も高いルールが採用される。
# ルールを追加する際はルールの先頭に簡単な例文を添えること
# ルールの評価は、現在の品詞と次の品詞に基づいて行われる。
rule {
  # 一般的な自立語
  # 例： 点字
  current_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "副詞"
    name: "形容詞"
    name: "接続詞"
  }
  # 一般的な自立語が続く
  # 例: 点字図書館
  next_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "人名"
    name: "動詞"
    name: "形容詞"
    name: "副詞"
    name: "接続詞"
    name: "形状詞"
    name: "接頭辞"
    name: "括弧開"
    before_space: true
  }
  # 上記空けるものでも、他の品詞に分類できる可能性があることがある者たち
  # 通常版 → 「版」は助数詞として使えるし、結び付きが強い
  # その人らしさ→「らしい」は形容詞的でもあるが、「接尾辞」として使える
  next_pos {
    name: "助数詞可能"
    name: "接尾辞"
    before_space: false
  }
}
# 人名: 一部特殊な扱いをする必要があるため、ルールを分ける
rule {
  current_pos {
    name: "人名"
  }
  # 人名の後に一般的な品詞が続く
  # 例: 山田太郎さん
  next_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "人名"
    name: "動詞"
    name: "形容詞"
    name: "副詞"
    name: "接続詞"
    name: "形状詞"
    name: "接頭辞"
    name: "括弧開"
    before_space: true
  }
  # 「さん」・「様」・「君」などの敬称は空ける
  # 例: 山田さん
  next_pos {
    name: "接尾辞"
    before_space: true
  }
}
# 助詞
# 例： が・は・へ・を・に…
# 多くの場合助詞の後は空ける
rule {
  current_pos {
    name: "助詞"
    name: "接尾辞"
  }
  # 助詞が・助動詞が続く
  # 例: 私のが、見ました → 「まし」・「た」はどちらも助動詞
  # 例: 花のように → 「よう」は助動詞の語幹になりうる
  next_pos {
    name: "助詞"
    name: "助動詞"
    name: "助動詞語幹"
    before_space: false
  }
  # 句読点など
  # 変換して、→「て」は助詞
  next_pos {
    name: "句点"
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "括弧閉"
    before_space: false
  }
  # その他の記号
  next_pos {
    name: "補助記号"
    word_match: "・"
    word_match: "："
    word_match: "；"
    before_space: false
  }
  # その他の品詞が続く
  # 私の椅子
  next_pos {
    name: "*"
    before_space: true
  }
}
# 動詞
# 例： 行く・来る・する…
# 動詞の後は空ける
rule {
  current_pos {
    name: "動詞"
    name: "助動詞"
  }
  # 自立語
  # 例: 走る人
  next_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "人名"
    name: "動詞"
    name: "形容詞"
    name: "形状詞"
    name: "接頭辞"
    name: "括弧開"
    before_space: true
  }
  # 申すそうだ
    next_pos {
    name: "助動詞語幹"
    before_space: false
  }
  # 歌わされる
  next_pos {
    name: "未然形-サ"
    before_space: false
  }
  # 句読点など
  next_pos {
    name: "補助記号"
    word_match: "！"
    word_match: "。"
    word_match: "、"
    word_match: "・"
    word_match: "？"
    word_match: "："
    word_match: "；"
    before_space: false
  }
  next_pos {
    name: "括弧閉"
    before_space: false
  }
}
rule {
  current_pos {
    name: "連体詞"
  }
  next_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "人名"
    name: "動詞"
    name: "形容詞"
    name: "副詞"
    name: "形状詞"
    name: "接続詞"
    name: "接頭辞"
    name: "連体詞"
    name: "括弧開"
    before_space: true
  }
  next_pos {
    name: "助動詞語幹"
    before_space: false
  }
}
# 数字とそれに関連するルール
# 例： 2025年
rule {
  current_pos {
    name: "数詞"
    name: "助数詞"
    name: "助数詞可能"
  }
  # 助数詞など
  # 例: １冊・９０年代・３冊の
  next_pos {
    name: "助数詞"
    name: "助数詞可能"
    name: "助詞"
    before_space: false
  }
  # 助数詞の後に一般的な品詞が続く
  # 例: １軒となりのいえ
  next_pos {
    name: "名詞"
    name: "代名詞"
    name: "固有名詞"
    name: "人名"
    name: "形容詞"
    name: "動詞"
    name: "副詞"
    name: "括弧開"
    before_space: true
  }
}
# 語の繋がりによる分類
# 影響が大きいので、一度無効化
# rule {
#   current_pos {
#     name: "連用形-一般"
#   }
#   # 連用形-一般の後に動詞が続く
#   # 例: 走り出す
#   next_pos {
#     name: "動詞"
#     name: "助動詞"
#     before_space: false
#   }
# }
# フォールバックルール
# その他の品詞はとりあえず続けてみる
rule {
  current_pos {
    name: "*"
  }
  # 句読点などの記号
  # 実例は設定参照
  next_pos {
    name: "補助記号"
    before_space: false
  }
}
