# 日本語の品詞に基づくルール
# ルールの先頭から順番に評価され、スコアがつけられる。スコアが最も高いルールが採用される。
# ルールを追加する際はルールの先頭に簡単な例文を添えること
# 2文字以下の名詞 : 北アメリカ
rule {
  current_pos {
    name: "名詞"
    reading_word_length_less: 2
  }
  next_pos {
    name: "名詞"
    before_space: false
  }
  next_pos {
    name: "助動詞"
    before_space: false
  }
  next_pos {
    name: "助詞"
    before_space: false
  }
  next_pos {
    name: "接続詞"
    before_space: false
  }
  next_pos {
    name: "接続助詞"
    before_space: false
  }
  next_pos {
    name: "接尾辞"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "中点"
    before_space: false
  }
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "括弧閉"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "名詞"
  }
  next_pos {
    name: "名詞"
    reading_word_length_less: 2
    before_space: false
  }
  next_pos {
    name: "助動詞"
    before_space: false
  }
  next_pos {
    name: "助詞"
    before_space: false
  }
  next_pos {
    name: "接続詞"
    before_space: false
  }
  next_pos {
    name: "接続助詞"
    before_space: false
  }
  next_pos {
    name: "接尾辞"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "中点"
    before_space: false
  }
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "括弧閉"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "代名詞"
  }
  next_pos {
    name: "助動詞"
    before_space: false
  }
  next_pos {
    name: "助詞"
    before_space: false
  }
  next_pos {
    name: "接続詞"
    before_space: false
  }
  next_pos {
    name: "接続助詞"
    before_space: false
  }
  next_pos {
    name: "接尾辞"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "中点"
    before_space: false
  }
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "括弧閉"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "動詞"
  }
  # 駆け抜ける、言いそびれる
  next_pos {
    name: "動詞"
    before_space: false
  }
  next_pos {
    name: "助詞"
    before_space: false
  }
  next_pos {
    name: "助動詞"
    before_space: false
  }
  next_pos {
    name: "助動詞語幹"
    before_space: false
  }
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "助動詞"
  }
  next_pos {
    name: "助詞"
    before_space: false
  }
  next_pos {
    name: "助動詞"
    before_space: false
  }
  next_pos {
    name: "助動詞語幹"
    before_space: false
  }
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "中点"
    before_space: false
  }
  next_pos {
    name: "括弧閉"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "助詞"
  }
  next_pos {
    name: "助詞"
    before_space: false
  }
  next_pos {
    name: "助動詞"
    before_space: false
  }
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "中点"
    before_space: false
  }
  next_pos {
    name: "括弧閉"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "係助詞"
  }
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "形容詞"
  }
  next_pos {
    name: "助詞"
    before_space: false
  }
  next_pos {
    name: "接尾辞"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
    next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "副詞"
  }
  # おそらくは
  next_pos {
    name: "助詞"
    before_space: false
  }
  # おそらく、
  next_pos {
    name: "読点"
    before_space: false
  }
  # おそらく。
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "数詞"
  }
  next_pos {
    name: "助数詞可能"
    before_space: false
  }
}
rule {
  current_pos {
    name: "連体詞"
  }
  next_pos {
    name: "形状詞"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "助数詞可能"
  }
  next_pos {
    name: "助数詞可能"
    before_space: false
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "接続詞"
  }
  next_pos {
    name: "助詞"
    before_space: false
  }
  next_pos {
    name: "助動詞"
    before_space: false
  }
  next_pos {
    name: "句点"
    before_space: false
  }
  next_pos {
    name: "読点"
    before_space: false
  }
  next_pos {
    name: "中点"
    before_space: false
  }
  next_pos {
    name: "括弧閉"
    before_space: false
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
rule {
  current_pos {
    name: "接頭辞"
  }
  next_pos {
    name: "名詞"
    before_space: false
  }
}
rule {
  current_pos {
    name: "接尾辞"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  next_pos {
    name: "動詞"
    before_space: true
  }
  next_pos {
    name: "形容詞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "形状詞"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  # あんなちっぽけな動物
  next_pos {
    name: "形状詞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "人名"
  }
  next_pos {
    name: "人名"
    before_space: true
  }
  next_pos {
    name: "接尾辞"
    before_space: true
  }
}
rule {
  current_pos {
    name: "接頭辞"
  }
  next_pos {
    name: "*"
    before_space: true
  }
}
# 影響が大きいようなので、一度無効化してみよう。
# 品詞での分類ではなく、なにとつながっているかに着目した分類。うまくいけば、この方法で分類できるかもしれない。
# rule {
#   current_pos {
#     name: "連用形-一般"
#   }
#   next_pos {
#     name: "接続助詞"
#     before_space: false
#   }
#   next_pos {
#     name: "*"
#     before_space: true
#   }
# }
rule {
  current_pos {
    name: "括弧閉"
  }
  next_pos {
    name: "名詞"
    before_space: true
  }
  next_pos {
    name: "代名詞"
    before_space: true
  }
  next_pos {
    name: "動詞"
    before_space: true
  }
  next_pos {
    name: "*"
    before_space: false
  }
}
rule {
  current_pos{
    name: "*"
  }
  next_pos {
    name: "*"
    before_space: false
  }
}
