baseURL = 'https://momo.seiken-lab.com'
locale = 'ja'
title = 'Japanese Braille Translation Software: MOMO Project'
paginate = 5

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[minify]
disableXML = true
minifyOutput = true

[params]
description = 'Japanese Braille Translation Software MOMO Project'
author = 'Seiken Lab'
disableThemeToggle = false
ShowShareButtons = true
ShareButtons = ["x", "linkedin", "facebook"]
ShowPostNavLinks = true
# ShowBreadCrumbs = true
ShowCodeCopyButtons = true
# ShowWordCount = true
# ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
# hideSummary = true
showtoc = false
tocopen = false

[menu]
[[menu.main]]
identifier = "home"
name = "ホーム"
url = "/"
weight = 1
[[menu.main]]
identifier = "news"
name = "お知らせ"
url = "/news/"
weight = 2
[[menu.main]]
identifier = "editor"
name = "MOMO エディタ"
url = "/editor/"
weight = 3
[[menu.main]]
identifier = "converter"
name = "変換プログラム"
url = "/converter/"
weight = 4
[[menu.main]]
identifier = "api"
name = "MOMO API"
url = "/api/"
weight = 5
[[menu.main]]
identifier = "download"
name = "ダウンロード"
url = "/downloads/"
weight = 6
[[menu.main]]
identifier = "technology"
name = "技術情報"
url = "/technology/"
weight = 7

[[menu.main]]
identifier = "about"
name = "MOMO について"
url = "/about/"
weight = 100

